sudo: required
language: php
dist: trusty

php:
- 7.0

install:
- cp .env.testing .env
- chmod 775 vendor/laravel/dusk/bin/*
- travis_retry composer install --no-interaction

before_script:
- php artisan serve &
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- ./vendor/laravel/dusk/bin/chromedriver-linux &

script:
- php artisan dusk