sudo: required
dist: trusty

language: php
php:
  - '7.0'

addons:
  chrome: stable

install:
- chmod 755 vendor/laravel/dusk/bin
- cp .env.testing .env
- travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
- google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost:8000 &
- php artisan serve &

script:
- php artisan dusk