sudo: required
language: php
dist: trusty

php:
  - 7.0

addons:
  mariadb: '10.0'
  hosts:
    - bitefight.vm

install:
  - cp .env.test .env
  - php artisan key:generate
  - chmod 775 vendor/laravel/dusk/bin/*

before_script:
  - php artisan serve --port=80 > /var/log/artisan_serve.log 2>&1 &
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./vendor/laravel/dusk/bin/chromedriver-linux &

script:
  - php artisan dusk

after_failure:
  - sudo cat /var/log/artisan_serve.log

